"""initial schema

Revision ID: f73cfaadb277
Revises: 
Create Date: 2026-08-16 19:31:29.749074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73cfaadb277'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_normalized_name'), 'organizations', ['normalized_name'], unique=False)
    op.create_table('apps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('app_store_id', sa.String(length=255), nullable=True),
    sa.Column('package_name', sa.String(length=255), nullable=True),
    sa.Column('developer_name', sa.String(length=255), nullable=True),
    sa.Column('store_url', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('current_rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apps_app_store_id'), 'apps', ['app_store_id'], unique=False)
    op.create_index(op.f('ix_apps_id'), 'apps', ['id'], unique=False)
    op.create_index(op.f('ix_apps_organization_id'), 'apps', ['organization_id'], unique=False)
    op.create_index(op.f('ix_apps_package_name'), 'apps', ['package_name'], unique=False)
    op.create_index(op.f('ix_apps_platform'), 'apps', ['platform'], unique=False)
    op.create_table('app_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_metrics_app_id'), 'app_metrics', ['app_id'], unique=False)
    op.create_index(op.f('ix_app_metrics_id'), 'app_metrics', ['id'], unique=False)
    op.create_table('app_themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('theme_name', sa.String(length=100), nullable=False),
    sa.Column('theme_type', sa.String(length=50), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_themes_app_id'), 'app_themes', ['app_id'], unique=False)
    op.create_index(op.f('ix_app_themes_id'), 'app_themes', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('external_review_id', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('review_version', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'external_review_id', name='uq_app_external_review')
    )
    op.create_index(op.f('ix_reviews_app_id'), 'reviews', ['app_id'], unique=False)
    op.create_index(op.f('ix_reviews_external_review_id'), 'reviews', ['external_review_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_review_date'), 'reviews', ['review_date'], unique=False)
    op.create_table('review_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_analysis_id'), 'review_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_review_analysis_review_id'), 'review_analysis', ['review_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_analysis_review_id'), table_name='review_analysis')
    op.drop_index(op.f('ix_review_analysis_id'), table_name='review_analysis')
    op.drop_table('review_analysis')
    op.drop_index(op.f('ix_reviews_review_date'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_external_review_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_app_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_app_themes_id'), table_name='app_themes')
    op.drop_index(op.f('ix_app_themes_app_id'), table_name='app_themes')
    op.drop_table('app_themes')
    op.drop_index(op.f('ix_app_metrics_id'), table_name='app_metrics')
    op.drop_index(op.f('ix_app_metrics_app_id'), table_name='app_metrics')
    op.drop_table('app_metrics')
    op.drop_index(op.f('ix_apps_platform'), table_name='apps')
    op.drop_index(op.f('ix_apps_package_name'), table_name='apps')
    op.drop_index(op.f('ix_apps_organization_id'), table_name='apps')
    op.drop_index(op.f('ix_apps_id'), table_name='apps')
    op.drop_index(op.f('ix_apps_app_store_id'), table_name='apps')
    op.drop_table('apps')
    op.drop_index(op.f('ix_organizations_normalized_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
